.TH iprintf 3 "" "" ""
.SH SYNOPSIS
iprintf \- write formatted output (integer only)
.SH ANSI_SYNOPSIS
#include <stdio.h>
.br

int iprintf(const char *
.IR format ,
...);
.br
.SH TRAD_SYNOPSIS
#include <stdio.h>
.br

int iprintf(
.IR format 
[, 
.IR arg ,
...])
.br
char *
.IR format ;
.br
.SH DESCRIPTION
.BR iprintf 
is a restricted version of 
.BR printf :
it has the same
arguments and behavior, save that it cannot perform any floating-point
formatting: the 
.BR f ,
.BR g ,
.BR G ,
.BR e ,
and 
.BR F 
type specifiers
are not recognized.
.SH RETURNS
.BR iprintf 
returns the number of bytes in the output string,
save that the concluding 
.BR NULL 
is not counted.
.BR iprintf 
returns when the end of the format string is
encountered. If an error occurs, 
.BR iprintf 
returns 
.BR EOF .
.SH PORTABILITY
.BR iprintf 
is not required by ANSI C.

Supporting OS subroutines required: 
.BR close ,
.BR fstat ,
.BR isatty ,
.BR lseek ,
.BR read ,
.BR sbrk ,
.BR write .
.SH SOURCE
src/newlib/libc/stdio/iprintf.c
