.TH strcmp 3 "" "" ""
.SH SYNOPSIS
strcmp \- character string compare
.SH ANSI_SYNOPSIS
#include <string.h>
.br
int strcmp(const char *
.IR a ,
const char *
.IR b );
.br
.SH TRAD_SYNOPSIS
#include <string.h>
.br
int strcmp(
.IR a ,
.IR b )
.br
char *
.IR a ;
.br
char *
.IR b ;
.br
.SH DESCRIPTION
.BR strcmp 
compares the string at 
.IR a 
to
the string at 
.IR b .
.SH RETURNS
If 
.BR *<[a >>
sorts lexicographically after 
.BR *<[b >>,
.BR strcmp 
returns a number greater than zero. If the two
strings match, 
.BR strcmp 
returns zero. If 
.BR *<[a >>
sorts lexicographically before 
.BR *<[b >>,
.BR strcmp 
returns a
number less than zero.
.SH PORTABILITY
.BR strcmp 
is ANSI C.

.BR strcmp 
requires no supporting OS subroutines.
.SH QUICKREF
strcmp ansi pure
.SH SOURCE
src/newlib/libc/string/strcmp.c
